version: '3'
networks:
    service-net:
        driver: bridge
services:
    libre-nginx:
        container_name: libre-nginx
        build: ./nginx
        ports:
            - 880:80
        volumes:
            - ./www:/usr/share/nginx/html
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./nginx/logs:/var/log/nginx
        depends_on:
            - libre-php
        restart: always
        networks:
            - service-net
    libre-php:
        container_name: libre-php
        build: ./php
        depends_on:
            - libre-mysql
        volumes:
            - ./www:/usr/share/nginx/html
            - ./php/php.ini:/usr/local/etc/php/php.ini
            - ./php/logs:/usr/local/var/log
        restart: always
        networks:
            - service-net
    libre-mysql:
      restart: always
      image: mysql:5.7.18
      container_name: libre-mysql
      volumes:
        - ./mysql/mydir:/mydir
        - ./mysql/datadir:/var/lib/mysql
        - ./mysql/conf/my.cnf:/etc/my.cnf
        # 数据库还原目录 可将需要还原的sql文件放在这里
        - ./mysql/source:/docker-entrypoint-initdb.d
      environment:
        - "MYSQL_ROOT_PASSWORD=!Libre1219"
        # - "MYSQL_DATABASE=exam"
        - "TZ=Asia/Shanghai"
      ports:
        # 使用宿主机的3306端口映射到容器的3306端口
        # 宿主机：容器
        - 3306:3306

